language: objective-c
osx_image: xcode9.4

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
    - rvm install ruby-2.2.2
    - gem install cocoapods
    - gem install xcpretty -N
    - brew update
    - brew install swiftlint || true
    - cd splitterML && pod install

podfile: Podfile

script:

  - xcodebuild -workspace splitterML.xcworkspace -scheme splitterML -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5s' build test | xcpretty -c
  - swiftlint
