language: objective-c
osx_image: xcode10.0

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
    - rvm install ruby-2.2.2
    - gem install cocoapods
    - gem install xcpretty
    - brew update
    - brew install swiftlint || true
    - pod repo update
    - pod install --verbose


podfile: Podfile

script:
  - xcodebuild
    -workspace splitterML.xcworkspace
    -scheme splitterML
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone 5s'
    build
    test
    | xcpretty
